repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pinglin/conventional-pre-commit
    rev: v1.1.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/bufbuild/buf.git
    rev: v1.25.0
    hooks:
      - id: buf-generate
      - id: buf-format
      - id: buf-lint
