repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: common/openapi
      - id: trailing-whitespace
  - repo: https://github.com/pinglin/conventional-pre-commit
    rev: v1.1.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/bufbuild/buf.git
    rev: v1.43.0
    hooks:
      - id: buf-generate
  - repo: local
    hooks:
      - id: generate-openapi
        name: generate openapi
        entry: make openapi
        language: system
        pass_filenames: false
  - repo: https://github.com/bufbuild/buf.git
    rev: v1.43.0
    hooks:
      - id: buf-format
      - id: buf-lint
  - repo: local
    hooks:
      - id: validate-openapi
        name: validate openapi
        entry: make openapi-lint
        language: system
        pass_filenames: false
