extends: ["spectral:oas"]
rules:
  # When uploading the specs to readme.com, this field will be used to render
  # information about an endpoint.
  operation-description: error
  # Unused or missing tags produce an empty group in readme.com.
  operation-tag-defined: error

  # Exceptions

  # [`grpc-gateway` issue 3058](https://github.com/grpc-ecosystem/grpc-gateway/issues/3058):
  # Most tooling ignores keywords next to `$ref`. However, `grpc-gateway`
  # produces such keywords.
  no-$ref-siblings: off
  # `grpc-gateway` generates types for nested types, but sometimes these are
  # only used by requests (e.g. `ComponentDefinition.View`). Request structures
  # are defined as part of the endpoint definition, so these nested types end
  # up defined but not referenced.
  oas2-unused-definition: off
