name: Generate and push OpenAPI

on:
  pull_request:
    paths:
      - ./**.proto
      - buf.gen.yaml

jobs:
  gen-buf-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: bufbuild/buf-setup-action@v1
      - name: Checkout protobuf repository
        uses: actions/checkout@v3
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.botGPGPrivateKey }}
          passphrase: ${{ secrets.botGPGPassphrase }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
      - name: Generate OpenAPI definitions
        run: |
          buf generate
      - name: Lint generated OpenAPI definitions
        uses: mhiew/redoc-lint-github-action@v3
        with:
          # Named path parameters (e.g. `/admin/{pipeline.permalink}/lookUp`)
          # cause linter errors despite being unambiguously resolved.
          args: openapiv2/openapiv2.swagger.yaml --skip-rule=no-ambiguous-paths --skip-rule=no-identical-paths
      - name: Commit and push
        run: |
          if [[ `git status --porcelain` ]]; then
            git fetch origin
            git checkout "${GITHUB_HEAD_REF}"
            git add openapiv2
            git commit -S -m "chore: auto-gen by protobufs" -m "triggered by commit: https://github.com/instill-ai/protobufs/commit/${GITHUB_SHA}"
            git push -u origin "${GITHUB_HEAD_REF}"
          fi
