name: Generate and push OpenAPI

on:
  pull_request:
    paths:
      - '**.proto'
      - '**.proto.templ'
      - 'buf.gen.*.yaml'
      - 'Makefile'
      - 'scripts/generate-openapi-doc-info.sh'
      - 'common/openapi/**'

jobs:
  gen-buf-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: bufbuild/buf-setup-action@v1
      - name: Checkout protobuf repository
        uses: actions/checkout@v3
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.botGPGPrivateKey }}
          passphrase: ${{ secrets.botGPGPassphrase }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
      - name: Generate OpenAPI definitions
        run: |
          make openapi
      - name: Lint generated Core OpenAPI definitions
        uses: readmeio/rdme@v8
        with:
          rdme: openapi:validate openapiv2/core/service.swagger.yaml
      - name: Lint generated VDP OpenAPI definitions
        uses: readmeio/rdme@v8
        with:
          rdme: openapi:validate openapiv2/vdp/service.swagger.yaml
      - name: Lint generated Model OpenAPI definitions
        uses: readmeio/rdme@v8
        with:
          rdme: openapi:validate openapiv2/model/service.swagger.yaml
      - name: Lint generated Artifact OpenAPI definitions
        uses: readmeio/rdme@v8
        with:
          rdme: openapi:validate openapiv2/artifact/service.swagger.yaml
      - name: Lint generated App OpenAPI definitions
        uses: readmeio/rdme@v8
        with:
          rdme: openapi:validate openapiv2/app/service.swagger.yaml
      - name: Commit and push
        run: |
          if [[ `git status --porcelain` ]]; then
            git fetch origin
            git checkout "${GITHUB_HEAD_REF}"
            git add openapiv2
            git commit -S -m "chore: auto-gen by protobufs" -m "triggered by commit: https://github.com/instill-ai/protobufs/commit/${GITHUB_SHA}"
            git push -u origin "${GITHUB_HEAD_REF}"
          fi
