name: Generate and push OpenAPI

on:
  pull_request:
    paths:
      - '**.proto'
      - 'buf.gen.*.yaml'
      - 'Makefile'
      - 'scripts/generate-openapi-doc-info.sh'
      - '.spectral.yaml'

jobs:
  gen-buf-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: bufbuild/buf-setup-action@v1
      - name: Checkout protobuf repository
        uses: actions/checkout@v3
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.botGPGPrivateKey }}
          passphrase: ${{ secrets.botGPGPassphrase }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
      - name: Generate OpenAPI definitions
        env:
          BUF_TOKEN: ${{ secrets.botBufToken }}
        run: |
          make openapi
      - name: Lint generated OpenAPI definitions
        uses: stoplightio/spectral-action@latest
        with:
          file_glob: 'openapi/v2/*.swagger.yaml'
      - name: Commit and push
        run: |
          if [[ `git status --porcelain` ]]; then
            git fetch origin
            git checkout "${GITHUB_HEAD_REF}"
            git add openapi/v2
            git commit -S -m "chore: auto-gen by protobufs" -m "triggered by commit: https://github.com/instill-ai/protobufs/commit/${GITHUB_SHA}"
            git push -u origin "${GITHUB_HEAD_REF}"
          fi
